import type { Metadata } from "next";
import localFont from "next/font/local";
import { Header } from "@/components/shared/header";

import "./globals.css";

const nunito = localFont({
  src: "./fonts/Nunito-Italic-VariableFont_wght.ttf",
  variable: "--font-nunito",
  style: "normal",
  weight: "300 900",
});

export const metadata: Metadata = {
  title: "Pizza Day | Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.variable} antialiased`}>
        <Header />
        <main className="min-h-screen">{children}</main>
      </body>
    </html>
  );
}
